package com.garden.entity;

// Generated Jun 10, 2016 12:51:31 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Uselibary generated by hbm2java
 */
@Entity
@Table(name = "uselibary", catalog = "travelguild")
public class Uselibary implements java.io.Serializable {

	private int userlibary;
	private String usename;
	private String uplanname;
	private String utypeplan;
	private Float uphhight;
	private Float ulighthight;
	private Float uhumidityhight;
	private Float utemperaturehight;
	private Float humidityofsoilhight;
	private Integer udatefertilizer;
	private Integer udaygrowth;
	private Float uphlower;
	private Float ulightlower;
	private Float uhumiditylower;
	private Float utemperaturelower;
	private Float uhumidityofsoillower;

	public Uselibary() {
	}

	public Uselibary(int userlibary, String usename) {
		this.userlibary = userlibary;
		this.usename = usename;
	}

	public Uselibary(int userlibary, String usename, String uplanname,
			String utypeplan, Float uphhight, Float ulighthight,
			Float uhumidityhight, Float utemperaturehight,
			Float humidityofsoilhight, Integer udatefertilizer,
			Integer udaygrowth, Float uphlower, Float ulightlower,
			Float uhumiditylower, Float utemperaturelower,
			Float uhumidityofsoillower) {
		this.userlibary = userlibary;
		this.usename = usename;
		this.uplanname = uplanname;
		this.utypeplan = utypeplan;
		this.uphhight = uphhight;
		this.ulighthight = ulighthight;
		this.uhumidityhight = uhumidityhight;
		this.utemperaturehight = utemperaturehight;
		this.humidityofsoilhight = humidityofsoilhight;
		this.udatefertilizer = udatefertilizer;
		this.udaygrowth = udaygrowth;
		this.uphlower = uphlower;
		this.ulightlower = ulightlower;
		this.uhumiditylower = uhumiditylower;
		this.utemperaturelower = utemperaturelower;
		this.uhumidityofsoillower = uhumidityofsoillower;
	}

	@Id
	@Column(name = "userlibary", unique = true, nullable = false)
	public int getUserlibary() {
		return this.userlibary;
	}

	public void setUserlibary(int userlibary) {
		this.userlibary = userlibary;
	}

	@Column(name = "usename", nullable = false)
	public String getUsename() {
		return this.usename;
	}

	public void setUsename(String usename) {
		this.usename = usename;
	}

	@Column(name = "uplanname")
	public String getUplanname() {
		return this.uplanname;
	}

	public void setUplanname(String uplanname) {
		this.uplanname = uplanname;
	}

	@Column(name = "utypeplan")
	public String getUtypeplan() {
		return this.utypeplan;
	}

	public void setUtypeplan(String utypeplan) {
		this.utypeplan = utypeplan;
	}

	@Column(name = "uphhight", precision = 12, scale = 0)
	public Float getUphhight() {
		return this.uphhight;
	}

	public void setUphhight(Float uphhight) {
		this.uphhight = uphhight;
	}

	@Column(name = "ulighthight", precision = 12, scale = 0)
	public Float getUlighthight() {
		return this.ulighthight;
	}

	public void setUlighthight(Float ulighthight) {
		this.ulighthight = ulighthight;
	}

	@Column(name = "uhumidityhight", precision = 12, scale = 0)
	public Float getUhumidityhight() {
		return this.uhumidityhight;
	}

	public void setUhumidityhight(Float uhumidityhight) {
		this.uhumidityhight = uhumidityhight;
	}

	@Column(name = "utemperaturehight", precision = 12, scale = 0)
	public Float getUtemperaturehight() {
		return this.utemperaturehight;
	}

	public void setUtemperaturehight(Float utemperaturehight) {
		this.utemperaturehight = utemperaturehight;
	}

	@Column(name = "humidityofsoilhight", precision = 12, scale = 0)
	public Float getHumidityofsoilhight() {
		return this.humidityofsoilhight;
	}

	public void setHumidityofsoilhight(Float humidityofsoilhight) {
		this.humidityofsoilhight = humidityofsoilhight;
	}

	@Column(name = "udatefertilizer")
	public Integer getUdatefertilizer() {
		return this.udatefertilizer;
	}

	public void setUdatefertilizer(Integer udatefertilizer) {
		this.udatefertilizer = udatefertilizer;
	}

	@Column(name = "udaygrowth")
	public Integer getUdaygrowth() {
		return this.udaygrowth;
	}

	public void setUdaygrowth(Integer udaygrowth) {
		this.udaygrowth = udaygrowth;
	}

	@Column(name = "uphlower", precision = 12, scale = 0)
	public Float getUphlower() {
		return this.uphlower;
	}

	public void setUphlower(Float uphlower) {
		this.uphlower = uphlower;
	}

	@Column(name = "ulightlower", precision = 12, scale = 0)
	public Float getUlightlower() {
		return this.ulightlower;
	}

	public void setUlightlower(Float ulightlower) {
		this.ulightlower = ulightlower;
	}

	@Column(name = "uhumiditylower", precision = 12, scale = 0)
	public Float getUhumiditylower() {
		return this.uhumiditylower;
	}

	public void setUhumiditylower(Float uhumiditylower) {
		this.uhumiditylower = uhumiditylower;
	}

	@Column(name = "utemperaturelower", precision = 12, scale = 0)
	public Float getUtemperaturelower() {
		return this.utemperaturelower;
	}

	public void setUtemperaturelower(Float utemperaturelower) {
		this.utemperaturelower = utemperaturelower;
	}

	@Column(name = "uhumidityofsoillower", precision = 12, scale = 0)
	public Float getUhumidityofsoillower() {
		return this.uhumidityofsoillower;
	}

	public void setUhumidityofsoillower(Float uhumidityofsoillower) {
		this.uhumidityofsoillower = uhumidityofsoillower;
	}

}
