package com.garden.entities;

// Generated May 29, 2016 3:43:09 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "garden")
public class Account implements java.io.Serializable {

	private int userId;
	private String username;
	private String password;
	private String address;
	private int phonenumber;
	private String email;

	public Account() {
	}

	public Account(int userId, String username, String password,
			String address, int phonenumber, String email) {
		this.userId = userId;
		this.username = username;
		this.password = password;
		this.address = address;
		this.phonenumber = phonenumber;
		this.email = email;
	}

	@Id
	@Column(name = "userID", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "address", nullable = false, length = 50)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "phonenumber", nullable = false)
	public int getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(int phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
