package com.garden.entities;

// Generated May 29, 2016 3:43:09 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Index generated by hbm2java
 */
@Entity
@Table(name = "index", catalog = "garden")
public class Index implements java.io.Serializable {

	private int idsersor;
	private int plantid;
	private Integer sph;
	private Integer slight;
	private Integer shumidity;
	private Integer stemperature;
	private Integer stemperatureOfSoil;
	private Date time;

	public Index() {
	}

	public Index(int idsersor, int plantid) {
		this.idsersor = idsersor;
		this.plantid = plantid;
	}

	public Index(int idsersor, int plantid, Integer sph, Integer slight,
			Integer shumidity, Integer stemperature,
			Integer stemperatureOfSoil, Date time) {
		this.idsersor = idsersor;
		this.plantid = plantid;
		this.sph = sph;
		this.slight = slight;
		this.shumidity = shumidity;
		this.stemperature = stemperature;
		this.stemperatureOfSoil = stemperatureOfSoil;
		this.time = time;
	}

	@Id
	@Column(name = "IDSersor", unique = true, nullable = false)
	public int getIdsersor() {
		return this.idsersor;
	}

	public void setIdsersor(int idsersor) {
		this.idsersor = idsersor;
	}

	@Column(name = "plantid", nullable = false)
	public int getPlantid() {
		return this.plantid;
	}

	public void setPlantid(int plantid) {
		this.plantid = plantid;
	}

	@Column(name = "SPH")
	public Integer getSph() {
		return this.sph;
	}

	public void setSph(Integer sph) {
		this.sph = sph;
	}

	@Column(name = "SLight")
	public Integer getSlight() {
		return this.slight;
	}

	public void setSlight(Integer slight) {
		this.slight = slight;
	}

	@Column(name = "SHumidity")
	public Integer getShumidity() {
		return this.shumidity;
	}

	public void setShumidity(Integer shumidity) {
		this.shumidity = shumidity;
	}

	@Column(name = "STemperature")
	public Integer getStemperature() {
		return this.stemperature;
	}

	public void setStemperature(Integer stemperature) {
		this.stemperature = stemperature;
	}

	@Column(name = "StemperatureOfSoil")
	public Integer getStemperatureOfSoil() {
		return this.stemperatureOfSoil;
	}

	public void setStemperatureOfSoil(Integer stemperatureOfSoil) {
		this.stemperatureOfSoil = stemperatureOfSoil;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "time", length = 19)
	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

}
