package com.garden.entities;

// Generated May 29, 2016 3:43:09 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Plantofuser generated by hbm2java
 */
@Entity
@Table(name = "plantofuser", catalog = "garden")
public class Plantofuser implements java.io.Serializable {

	private int uplantId;
	private int userId;
	private String uplantname;
	private int uph;
	private int ulight;
	private int uhumidity;
	private int utemperature;
	private int utemperatureofsoil;

	public Plantofuser() {
	}

	public Plantofuser(int uplantId, int userId, String uplantname, int uph,
			int ulight, int uhumidity, int utemperature, int utemperatureofsoil) {
		this.uplantId = uplantId;
		this.userId = userId;
		this.uplantname = uplantname;
		this.uph = uph;
		this.ulight = ulight;
		this.uhumidity = uhumidity;
		this.utemperature = utemperature;
		this.utemperatureofsoil = utemperatureofsoil;
	}

	@Id
	@Column(name = "uplantID", unique = true, nullable = false)
	public int getUplantId() {
		return this.uplantId;
	}

	public void setUplantId(int uplantId) {
		this.uplantId = uplantId;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "uplantname", nullable = false, length = 50)
	public String getUplantname() {
		return this.uplantname;
	}

	public void setUplantname(String uplantname) {
		this.uplantname = uplantname;
	}

	@Column(name = "uph", nullable = false)
	public int getUph() {
		return this.uph;
	}

	public void setUph(int uph) {
		this.uph = uph;
	}

	@Column(name = "ulight", nullable = false)
	public int getUlight() {
		return this.ulight;
	}

	public void setUlight(int ulight) {
		this.ulight = ulight;
	}

	@Column(name = "uhumidity", nullable = false)
	public int getUhumidity() {
		return this.uhumidity;
	}

	public void setUhumidity(int uhumidity) {
		this.uhumidity = uhumidity;
	}

	@Column(name = "utemperature", nullable = false)
	public int getUtemperature() {
		return this.utemperature;
	}

	public void setUtemperature(int utemperature) {
		this.utemperature = utemperature;
	}

	@Column(name = "utemperatureofsoil", nullable = false)
	public int getUtemperatureofsoil() {
		return this.utemperatureofsoil;
	}

	public void setUtemperatureofsoil(int utemperatureofsoil) {
		this.utemperatureofsoil = utemperatureofsoil;
	}

}
