package com.garden.entities;

// Generated May 29, 2016 3:43:09 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Plant generated by hbm2java
 */
@Entity
@Table(name = "plant", catalog = "garden")
public class Plant implements java.io.Serializable {

	private int plantid;
	private String plantname;
	private String varieties;

	public Plant() {
	}

	public Plant(int plantid, String plantname) {
		this.plantid = plantid;
		this.plantname = plantname;
	}

	public Plant(int plantid, String plantname, String varieties) {
		this.plantid = plantid;
		this.plantname = plantname;
		this.varieties = varieties;
	}

	@Id
	@Column(name = "plantid", unique = true, nullable = false)
	public int getPlantid() {
		return this.plantid;
	}

	public void setPlantid(int plantid) {
		this.plantid = plantid;
	}

	@Column(name = "plantname", nullable = false, length = 50)
	public String getPlantname() {
		return this.plantname;
	}

	public void setPlantname(String plantname) {
		this.plantname = plantname;
	}

	@Column(name = "varieties", length = 50)
	public String getVarieties() {
		return this.varieties;
	}

	public void setVarieties(String varieties) {
		this.varieties = varieties;
	}

}
