package com.garden.entities;

// Generated May 29, 2016 3:43:09 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transfer generated by hbm2java
 */
@Entity
@Table(name = "transfer", catalog = "garden")
public class Transfer implements java.io.Serializable {

	private int transferid;
	private Integer plantid;
	private Date startpump;
	private Integer durationpump;
	private Date startcovered;
	private Integer durationstartcovered;
	private Date startmisting;
	private Integer durationmisting;
	private Date startduty;
	private Date starday;
	private Integer durations;

	public Transfer() {
	}

	public Transfer(int transferid) {
		this.transferid = transferid;
	}

	public Transfer(int transferid, Integer plantid, Date startpump,
			Integer durationpump, Date startcovered,
			Integer durationstartcovered, Date startmisting,
			Integer durationmisting, Date startduty, Date starday,
			Integer durations) {
		this.transferid = transferid;
		this.plantid = plantid;
		this.startpump = startpump;
		this.durationpump = durationpump;
		this.startcovered = startcovered;
		this.durationstartcovered = durationstartcovered;
		this.startmisting = startmisting;
		this.durationmisting = durationmisting;
		this.startduty = startduty;
		this.starday = starday;
		this.durations = durations;
	}

	@Id
	@Column(name = "transferid", unique = true, nullable = false)
	public int getTransferid() {
		return this.transferid;
	}

	public void setTransferid(int transferid) {
		this.transferid = transferid;
	}

	@Column(name = "plantid")
	public Integer getPlantid() {
		return this.plantid;
	}

	public void setPlantid(Integer plantid) {
		this.plantid = plantid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startpump", length = 19)
	public Date getStartpump() {
		return this.startpump;
	}

	public void setStartpump(Date startpump) {
		this.startpump = startpump;
	}

	@Column(name = "durationpump")
	public Integer getDurationpump() {
		return this.durationpump;
	}

	public void setDurationpump(Integer durationpump) {
		this.durationpump = durationpump;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startcovered", length = 19)
	public Date getStartcovered() {
		return this.startcovered;
	}

	public void setStartcovered(Date startcovered) {
		this.startcovered = startcovered;
	}

	@Column(name = "durationstartcovered")
	public Integer getDurationstartcovered() {
		return this.durationstartcovered;
	}

	public void setDurationstartcovered(Integer durationstartcovered) {
		this.durationstartcovered = durationstartcovered;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startmisting", length = 19)
	public Date getStartmisting() {
		return this.startmisting;
	}

	public void setStartmisting(Date startmisting) {
		this.startmisting = startmisting;
	}

	@Column(name = "durationmisting")
	public Integer getDurationmisting() {
		return this.durationmisting;
	}

	public void setDurationmisting(Integer durationmisting) {
		this.durationmisting = durationmisting;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "startduty", length = 19)
	public Date getStartduty() {
		return this.startduty;
	}

	public void setStartduty(Date startduty) {
		this.startduty = startduty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "starday", length = 19)
	public Date getStarday() {
		return this.starday;
	}

	public void setStarday(Date starday) {
		this.starday = starday;
	}

	@Column(name = "durations")
	public Integer getDurations() {
		return this.durations;
	}

	public void setDurations(Integer durations) {
		this.durations = durations;
	}

}
