package com.myprojet.entities;

// Generated Jun 10, 2016 10:34:30 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Place generated by hbm2java
 */
@Entity
@Table(name = "place", catalog = "travelguild")
public class Place implements java.io.Serializable {

	private Integer placeId;
	private String placeName;
	private String placeDescription;
	private Integer provinceId;
	private String placeImgLink;
	private Integer placeVote;

	public Place() {
	}

	public Place(String placeName, String placeDescription, Integer provinceId,
			String placeImgLink, Integer placeVote) {
		this.placeName = placeName;
		this.placeDescription = placeDescription;
		this.provinceId = provinceId;
		this.placeImgLink = placeImgLink;
		this.placeVote = placeVote;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "placeId", unique = true, nullable = false)
	public Integer getPlaceId() {
		return this.placeId;
	}

	public void setPlaceId(Integer placeId) {
		this.placeId = placeId;
	}

	@Column(name = "placeName")
	public String getPlaceName() {
		return this.placeName;
	}

	public void setPlaceName(String placeName) {
		this.placeName = placeName;
	}

	@Column(name = "placeDescription")
	public String getPlaceDescription() {
		return this.placeDescription;
	}

	public void setPlaceDescription(String placeDescription) {
		this.placeDescription = placeDescription;
	}

	@Column(name = "provinceId")
	public Integer getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	@Column(name = "placeImgLink")
	public String getPlaceImgLink() {
		return this.placeImgLink;
	}

	public void setPlaceImgLink(String placeImgLink) {
		this.placeImgLink = placeImgLink;
	}

	@Column(name = "placeVote")
	public Integer getPlaceVote() {
		return this.placeVote;
	}

	public void setPlaceVote(Integer placeVote) {
		this.placeVote = placeVote;
	}

}
