package com.myprojet.entities;

// Generated Jun 10, 2016 10:34:30 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Province generated by hbm2java
 */
@Entity
@Table(name = "province", catalog = "travelguild")
public class Province implements java.io.Serializable {

	private Integer provinceId;
	private String provinceName;
	private String provinceDescription;
	private Integer areaId;

	public Province() {
	}

	public Province(String provinceName, String provinceDescription,
			Integer areaId) {
		this.provinceName = provinceName;
		this.provinceDescription = provinceDescription;
		this.areaId = areaId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "provinceId", unique = true, nullable = false)
	public Integer getProvinceId() {
		return this.provinceId;
	}

	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	@Column(name = "provinceName")
	public String getProvinceName() {
		return this.provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	@Column(name = "provinceDescription")
	public String getProvinceDescription() {
		return this.provinceDescription;
	}

	public void setProvinceDescription(String provinceDescription) {
		this.provinceDescription = provinceDescription;
	}

	@Column(name = "areaId")
	public Integer getAreaId() {
		return this.areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

}
