package com.myprojet.entities;

// Generated Jun 10, 2016 10:34:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sensorinfo generated by hbm2java
 */
@Entity
@Table(name = "sensorinfo", catalog = "travelguild")
public class Sensorinfo implements java.io.Serializable {

	private Integer id;
	private int zoneId;
	private float ph;
	private float light;
	private float humidity;
	private float temperature;
	private float soilMoisture;
	private Date synctime;

	public Sensorinfo() {
	}

	public Sensorinfo(int zoneId, float ph, float light, float humidity,
			float temperature, float soilMoisture, Date synctime) {
		this.zoneId = zoneId;
		this.ph = ph;
		this.light = light;
		this.humidity = humidity;
		this.temperature = temperature;
		this.soilMoisture = soilMoisture;
		this.synctime = synctime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "zoneID", nullable = false)
	public int getZoneId() {
		return this.zoneId;
	}

	public void setZoneId(int zoneId) {
		this.zoneId = zoneId;
	}

	@Column(name = "ph", nullable = false, precision = 12, scale = 0)
	public float getPh() {
		return this.ph;
	}

	public void setPh(float ph) {
		this.ph = ph;
	}

	@Column(name = "light", nullable = false, precision = 12, scale = 0)
	public float getLight() {
		return this.light;
	}

	public void setLight(float light) {
		this.light = light;
	}

	@Column(name = "humidity", nullable = false, precision = 12, scale = 0)
	public float getHumidity() {
		return this.humidity;
	}

	public void setHumidity(float humidity) {
		this.humidity = humidity;
	}

	@Column(name = "temperature", nullable = false, precision = 12, scale = 0)
	public float getTemperature() {
		return this.temperature;
	}

	public void setTemperature(float temperature) {
		this.temperature = temperature;
	}

	@Column(name = "soilMoisture", nullable = false, precision = 12, scale = 0)
	public float getSoilMoisture() {
		return this.soilMoisture;
	}

	public void setSoilMoisture(float soilMoisture) {
		this.soilMoisture = soilMoisture;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "synctime", nullable = false, length = 19)
	public Date getSynctime() {
		return this.synctime;
	}

	public void setSynctime(Date synctime) {
		this.synctime = synctime;
	}

}
