package com.myprojet.entities;

// Generated Jun 10, 2016 10:34:30 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Userlibrary generated by hbm2java
 */
@Entity
@Table(name = "userlibrary", catalog = "travelguild")
public class Userlibrary implements java.io.Serializable {

	private Integer userLibId;
	private String username;
	private String userPlanName;
	private String userTypePlan;
	private Float userHighPh;
	private Float userLowPh;
	private Float userHighLight;
	private Float userLowLight;
	private Float userHighHumidity;
	private Float userLowHumidity;
	private Float userHighTemperature;
	private Float userLowTemperature;
	private Float userHighSoilMoisture;
	private Float userLowSoilMoisture;
	private Date userFertilizeDate;
	private Float userWeightFertilize;
	private Integer userLifeCycleOfPlan;

	public Userlibrary() {
	}

	public Userlibrary(String username, String userPlanName, String userTypePlan) {
		this.username = username;
		this.userPlanName = userPlanName;
		this.userTypePlan = userTypePlan;
	}

	public Userlibrary(String username, String userPlanName,
			String userTypePlan, Float userHighPh, Float userLowPh,
			Float userHighLight, Float userLowLight, Float userHighHumidity,
			Float userLowHumidity, Float userHighTemperature,
			Float userLowTemperature, Float userHighSoilMoisture,
			Float userLowSoilMoisture, Date userFertilizeDate,
			Float userWeightFertilize, Integer userLifeCycleOfPlan) {
		this.username = username;
		this.userPlanName = userPlanName;
		this.userTypePlan = userTypePlan;
		this.userHighPh = userHighPh;
		this.userLowPh = userLowPh;
		this.userHighLight = userHighLight;
		this.userLowLight = userLowLight;
		this.userHighHumidity = userHighHumidity;
		this.userLowHumidity = userLowHumidity;
		this.userHighTemperature = userHighTemperature;
		this.userLowTemperature = userLowTemperature;
		this.userHighSoilMoisture = userHighSoilMoisture;
		this.userLowSoilMoisture = userLowSoilMoisture;
		this.userFertilizeDate = userFertilizeDate;
		this.userWeightFertilize = userWeightFertilize;
		this.userLifeCycleOfPlan = userLifeCycleOfPlan;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "userLibID", unique = true, nullable = false)
	public Integer getUserLibId() {
		return this.userLibId;
	}

	public void setUserLibId(Integer userLibId) {
		this.userLibId = userLibId;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "userPlanName", nullable = false)
	public String getUserPlanName() {
		return this.userPlanName;
	}

	public void setUserPlanName(String userPlanName) {
		this.userPlanName = userPlanName;
	}

	@Column(name = "userTypePlan", nullable = false)
	public String getUserTypePlan() {
		return this.userTypePlan;
	}

	public void setUserTypePlan(String userTypePlan) {
		this.userTypePlan = userTypePlan;
	}

	@Column(name = "userHighPH", precision = 12, scale = 0)
	public Float getUserHighPh() {
		return this.userHighPh;
	}

	public void setUserHighPh(Float userHighPh) {
		this.userHighPh = userHighPh;
	}

	@Column(name = "userLowPH", precision = 12, scale = 0)
	public Float getUserLowPh() {
		return this.userLowPh;
	}

	public void setUserLowPh(Float userLowPh) {
		this.userLowPh = userLowPh;
	}

	@Column(name = "userHighLight", precision = 12, scale = 0)
	public Float getUserHighLight() {
		return this.userHighLight;
	}

	public void setUserHighLight(Float userHighLight) {
		this.userHighLight = userHighLight;
	}

	@Column(name = "userLowLight", precision = 12, scale = 0)
	public Float getUserLowLight() {
		return this.userLowLight;
	}

	public void setUserLowLight(Float userLowLight) {
		this.userLowLight = userLowLight;
	}

	@Column(name = "userHighHumidity", precision = 12, scale = 0)
	public Float getUserHighHumidity() {
		return this.userHighHumidity;
	}

	public void setUserHighHumidity(Float userHighHumidity) {
		this.userHighHumidity = userHighHumidity;
	}

	@Column(name = "userLowHumidity", precision = 12, scale = 0)
	public Float getUserLowHumidity() {
		return this.userLowHumidity;
	}

	public void setUserLowHumidity(Float userLowHumidity) {
		this.userLowHumidity = userLowHumidity;
	}

	@Column(name = "userHighTemperature", precision = 12, scale = 0)
	public Float getUserHighTemperature() {
		return this.userHighTemperature;
	}

	public void setUserHighTemperature(Float userHighTemperature) {
		this.userHighTemperature = userHighTemperature;
	}

	@Column(name = "userLowTemperature", precision = 12, scale = 0)
	public Float getUserLowTemperature() {
		return this.userLowTemperature;
	}

	public void setUserLowTemperature(Float userLowTemperature) {
		this.userLowTemperature = userLowTemperature;
	}

	@Column(name = "userHighSoilMoisture", precision = 12, scale = 0)
	public Float getUserHighSoilMoisture() {
		return this.userHighSoilMoisture;
	}

	public void setUserHighSoilMoisture(Float userHighSoilMoisture) {
		this.userHighSoilMoisture = userHighSoilMoisture;
	}

	@Column(name = "userLowSoilMoisture", precision = 12, scale = 0)
	public Float getUserLowSoilMoisture() {
		return this.userLowSoilMoisture;
	}

	public void setUserLowSoilMoisture(Float userLowSoilMoisture) {
		this.userLowSoilMoisture = userLowSoilMoisture;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "userFertilizeDate", length = 19)
	public Date getUserFertilizeDate() {
		return this.userFertilizeDate;
	}

	public void setUserFertilizeDate(Date userFertilizeDate) {
		this.userFertilizeDate = userFertilizeDate;
	}

	@Column(name = "userWeightFertilize", precision = 12, scale = 0)
	public Float getUserWeightFertilize() {
		return this.userWeightFertilize;
	}

	public void setUserWeightFertilize(Float userWeightFertilize) {
		this.userWeightFertilize = userWeightFertilize;
	}

	@Column(name = "userLifeCycleOfPlan")
	public Integer getUserLifeCycleOfPlan() {
		return this.userLifeCycleOfPlan;
	}

	public void setUserLifeCycleOfPlan(Integer userLifeCycleOfPlan) {
		this.userLifeCycleOfPlan = userLifeCycleOfPlan;
	}

}
